### ISSUE TITLE
bear

### ISSUE THREAD

**Issue by missingbinaries** [loli-services/haste#1]
![](https://cdn.discordapp.com/emojis/476421923216162819.gif?v=1)

**Comment by ohlookitsAugust** [comment]
i agree

**Comment by ohlookitsAugust** [comment]
all of u are qt

**Comment by xXBuilderBXx** [comment]
<@280158289667555328> is qt and should get in my bed mmhhhh

**Comment by ohlookitsAugust** [comment]
ok

![](https://cdn.discordapp.com/emojis/476421923404906506.gif?v=1)

**Comment by ohlookitsderpy** [comment]
![bigbear5](https://user-images.githubusercontent.com/14052956/46573137-8b9f2c80-c988-11e8-8764-0316e873403a.gif)

**Comment by missingbinaries** [comment]
qt

**Comment by missingbinaries** [comment]
bear

**Comment by missingbinaries** [comment]
ok
